/**
 * Production reports — generates printable HTML for the browser's native
 * print dialog (which gives the user "Save as PDF" on every platform).
 *
 * Reports:
 *   - shot-list:    every scene → table of its shots (#, type, camera, lens,
 *                    duration, description, b-roll count)
 *   - cast-list:     every character with key fields
 *   - location-list: extracted from scene-heading INT./EXT. strings
 */

import type { AppState } from '@/types';

export type ReportKind = 'shot-list' | 'cast-list' | 'location-list';

function escape(s: string): string {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}

function htmlShell(title: string, body: string): string {
  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<title>${escape(title)}</title>
<style>
  body { font-family: -apple-system, BlinkMacSystemFont, sans-serif; font-size: 11pt; color: #111; margin: 24px; }
  h1 { font-size: 18pt; border-bottom: 2px solid #333; padding-bottom: 4pt; margin: 0 0 12pt; }
  h2 { font-size: 13pt; margin: 18pt 0 4pt; color: #222; }
  table { width: 100%; border-collapse: collapse; margin-bottom: 12pt; }
  th, td { text-align: left; padding: 4pt 6pt; border-bottom: 1px solid #ddd; font-size: 10pt; vertical-align: top; }
  th { background: #f4f4f5; font-weight: 700; text-transform: uppercase; font-size: 8pt; letter-spacing: 0.04em; color: #444; }
  tr:nth-child(even) td { background: #fafafa; }
  .muted { color: #888; font-style: italic; }
  .meta { color: #555; font-size: 9pt; margin-bottom: 12pt; }
  @media print {
    body { margin: 12mm; }
  }
</style>
</head>
<body>
${body}
<p class="meta">Generated by Kindling · ${new Date().toLocaleString()}</p>
<script>setTimeout(function(){ window.print(); }, 200);</script>
</body>
</html>`;
}

export function buildReport(state: Partial<AppState>, kind: ReportKind, storyTitle: string): string {
  if (kind === 'shot-list') return shotList(state, storyTitle);
  if (kind === 'cast-list') return castList(state, storyTitle);
  return locationList(state, storyTitle);
}

function shotList(state: Partial<AppState>, storyTitle: string): string {
  const scenes = state.scenes || [];
  const shots = state.shots || {};
  const bRolls = state.bRolls || {};
  let body = `<h1>Shot List — ${escape(storyTitle)}</h1>`;
  if (scenes.length === 0) {
    body += '<p class="muted">No scenes yet.</p>';
    return htmlShell(`Shot List · ${storyTitle}`, body);
  }
  for (const sc of scenes) {
    const sceneShots = sc.shotIds.map((id) => shots[id]).filter(Boolean);
    body += `<h2>${escape(sc.name || sc.heading || '(untitled scene)')}</h2>`;
    if (sceneShots.length === 0) {
      body += '<p class="muted">No shots.</p>';
      continue;
    }
    body += `<table>
      <thead><tr>
        <th>#</th><th>Type</th><th>Camera / movement</th><th>Lens</th><th>Dur</th><th>Description</th><th>B-roll</th>
      </tr></thead><tbody>`;
    sceneShots.forEach((shot, i) => {
      const brollCount = shot.bRollIds.filter((b) => bRolls[b]).length;
      body += `<tr>
        <td>${i + 1}</td>
        <td>${escape(shot.shotType || '')}</td>
        <td>${escape(shot.camera || '')}</td>
        <td>${escape(shot.lens || '')}</td>
        <td>${shot.durationSec ? shot.durationSec + 's' : ''}</td>
        <td>${escape(shot.description || '')}</td>
        <td>${brollCount || ''}</td>
      </tr>`;
    });
    body += '</tbody></table>';
  }
  return htmlShell(`Shot List · ${storyTitle}`, body);
}

function castList(state: Partial<AppState>, storyTitle: string): string {
  const cs = state.characters || [];
  let body = `<h1>Cast List — ${escape(storyTitle)}</h1>`;
  if (cs.length === 0) {
    body += '<p class="muted">No characters yet.</p>';
    return htmlShell(`Cast List · ${storyTitle}`, body);
  }
  body += `<table>
    <thead><tr>
      <th>Name</th><th>Age</th><th>Occupation</th><th>Archetype</th><th>Want / Need</th><th>Conflict</th>
    </tr></thead><tbody>`;
  for (const c of cs) {
    const wantNeed = [c.want, c.need].filter(Boolean).join(' / ');
    body += `<tr>
      <td><strong>${escape(c.name || '')}</strong></td>
      <td>${escape(c.age || '')}</td>
      <td>${escape(c.occupation || '')}</td>
      <td>${escape((c as any).archetype || '')}</td>
      <td>${escape(wantNeed || '')}</td>
      <td>${escape(c.conflict || '')}</td>
    </tr>`;
  }
  body += '</tbody></table>';
  return htmlShell(`Cast List · ${storyTitle}`, body);
}

function locationList(state: Partial<AppState>, storyTitle: string): string {
  const scenes = state.scenes || [];
  const sp = state.screenplay;
  // Pull location strings from scene names (Director) and scene-heading
  // elements in the writer document.
  const locs = new Map<string, { count: number; firstSceneName: string }>();
  const addLoc = (raw: string, sceneName: string) => {
    const m = raw.match(/^(INT\.|EXT\.|EST\.|I\/E\.)\s*(.+?)(?:\s*[-–—]\s*(?:DAY|NIGHT|DAWN|DUSK|MORNING|EVENING|CONTINUOUS|LATER)\s*)?$/i);
    const place = (m ? m[2] : raw).trim().toUpperCase();
    if (!place) return;
    const entry = locs.get(place);
    if (entry) entry.count++;
    else locs.set(place, { count: 1, firstSceneName: sceneName });
  };
  for (const sc of scenes) addLoc(sc.heading || sc.name, sc.name || sc.heading);
  if (sp) {
    for (const el of sp.elements || []) {
      if (el.type === 'scene-heading') addLoc(el.content.replace(/<[^>]+>/g, ''), '');
    }
  }
  let body = `<h1>Location List — ${escape(storyTitle)}</h1>`;
  if (locs.size === 0) {
    body += '<p class="muted">No scene headings found.</p>';
    return htmlShell(`Location List · ${storyTitle}`, body);
  }
  const sorted = [...locs.entries()].sort((a, b) => b[1].count - a[1].count);
  body += `<table>
    <thead><tr><th>Location</th><th>Scenes</th><th>First seen in</th></tr></thead><tbody>`;
  for (const [place, info] of sorted) {
    body += `<tr><td><strong>${escape(place)}</strong></td><td>${info.count}</td><td>${escape(info.firstSceneName)}</td></tr>`;
  }
  body += '</tbody></table>';
  return htmlShell(`Location List · ${storyTitle}`, body);
}

/**
 * Open the report HTML in a new tab and trigger the browser's print dialog.
 * Falls back to a Blob download if popups are blocked.
 */
export function openReport(html: string, suggestedTitle: string) {
  const w = window.open('about:blank', '_blank');
  if (w) {
    w.document.open();
    w.document.write(html);
    w.document.close();
    return;
  }
  // Popup blocked — fall back to download
  const blob = new Blob([html], { type: 'text/html;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${suggestedTitle.replace(/[^\w\- ]/g, '_')}.html`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}
